services:
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: 'always'
    ports:
      - 8090:8090
    volumes:
      - ./beszel_data:/beszel_data
      - ./beszel_socket:/beszel_socket
